python/Exercises/flask_login_blueprints/project/users/models.py
from project import db, bcrypt
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text, unique=True)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = bcrypt.generate_password_hash(password).decode('utf-8')

    def __repr__(self):
        return '<User %r>' % self.username

python/Exercises/flask_login_blueprints/project/users/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired

class SignupForm(Form):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])

class LoginForm(Form):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])

python/Exercises/flask_login_blueprints/app.py
from project import app

if __name__ == '__main__':
    app.run(debug=True, port=3000)

python/Exercises/flask_login_blueprints/project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

app = Flask(__name__)
bcrypt = Bcrypt(app)
login_manager = LoginManager()
login_manager.init_app(app)
app.secret_key = "i'll never tell" # put this in a .env file! https://github.com/theskumar/python-dotenv OR add this to your virtual environment!
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://localhost/flask_login_app_blueprint'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

from project.users.views import users_blueprint

# register our blueprints
app.register_blueprint(users_blueprint)

from project.users.models import User

login_manager.login_view = "users.login"

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()

python/Exercises/flask_login_blueprints/project/users/views.py
from flask import flash, redirect, render_template, request, url_for, Blueprint
from project.users.forms import LoginForm, SignupForm
from project.users.models import User, bcrypt
from project import db
from flask_login import login_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError

users_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates'
)

@users_blueprint.route('/')
def root():
    return redirect(url_for('users.login'))

@users_blueprint.route('/signup', methods =["GET", "POST"])
def signup():
    error = None
    form = SignupForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit() :
            user = User(
                username=form.username.data,
                email=form.email.data,
                password=form.password.data
                )
            try:
                db.session.add(user)
                db.session.commit()
                login_user(user)
                return redirect(url_for('users.home'))
            except IntegrityError:
                error = 'Username already exists'
                return render_template('signup.html', form=form, error=error)
        else:
            return render_template('signup.html', form=form, error=error)
    else:
        return render_template('signup.html', form=form, error=error)

@users_blueprint.route('/login', methods =["GET", "POST"])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                flash('Logged in!')
                return redirect(url_for('users.home'))
            else:
                error = 'Invalid Credentials. Please try again.'
        else:
            return render_template('login.html', form=form, error=error)
    return render_template('login.html', form=form, error=error)

@users_blueprint.route('/home')
@login_required
def home():
    return render_template('home.html')

@users_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Logged out')
    return redirect(url_for('users.login'))

python/Exercises/flask_login_blueprints/project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

</head>
<body>
    <!-- flash messages -->
    {% for message in get_flashed_messages() %}
      {{message}}
    {% endfor %}

    <!-- errors -->
    {% if error %}
      <p class="text-danger"><strong>Error:</strong> {{ error }}</p>
    {% endif %}

    {% block content %}
    {% endblock %}

</body>
</html>

python/Exercises/flask_login_blueprints/project/users/templates/home.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome Home {{current_user.username}}!</h1>
<a href="{{url_for('users.logout')}}">Logout</a>
{% endblock %}

python/Exercises/flask_login_blueprints/project/users/templates/login.html
{% extends 'base.html' %}
{% block content %}

<a href="{{url_for('users.signup')}}">Don't have an account? Sign up here</a>

<h1>Please login</h1>
<br>
<form method="post" action="/login">
  {{ form.csrf_token }}
  <p>
    {{ form.username(placeholder="username") }}
    <span class="text-danger">
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="password") }}
    <span class="text-danger">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Sign in</button>
</form>

{% endblock %}

python/Exercises/flask_login_blueprints/project/users/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<a href="{{url_for('users.login')}}">Have an account already? Log in here</a>

<h1>Signup</h1>
<br>
<form method="post" action="/signup">
  {{ form.csrf_token }}
  <p>
    {{ form.username(placeholder="username") }}
    <span class="text-danger">
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  <p>
    {{ form.email(placeholder="email") }}
    <span class="text-danger">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="password") }}
    <span class="text-danger">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Sign in</button>
</form>

{% endblock %}

python/Exercises/flask_login_blueprints/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}

    <!-- errors -->
    {% if error %}
      <p class="text-danger">Error: {{ error }}</p>
    {% endif %}

    <!-- flash messages -->
    {% for message in get_flashed_messages() %}
      {{message}}
    {% endfor %}
</body>
</html>