python/Exercises/flask_auth_multiple_resources/project/posts/models.py
from project import db

class Post(db.Model):

    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    body = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, title, body, user_id):
        self.title = title
        self.body = body
        self.user_id = user_id

    def __repr__(self):
        return "Title: {} \n Body: {}".format(self.title, self.body)

python/Exercises/flask_auth_multiple_resources/project/posts/forms.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired

class NewPostForm(Form):
    title = StringField('title', validators=[DataRequired()])
    body = StringField('body', validators=[DataRequired()])

class EditPostForm(Form):
    title = StringField('title', validators=[DataRequired()])
    body = StringField('body', validators=[DataRequired()])

python/Exercises/flask_auth_multiple_resources/project/posts/views.py
from flask import render_template, Blueprint, url_for, request, redirect, flash
from flask_login import login_required, current_user
from functools import wraps
from project import db
from project.posts.models import Post
from project.users.models import User
from project.posts.forms import NewPostForm, EditPostForm

posts_blueprint = Blueprint('posts', __name__, template_folder="templates")

# Helper for authorization
def ensure_correct_user():
    def wrapper(f):
        @wraps(f)
        def wrapped(*args, **kwargs):
            if current_user.id != request.view_args['user_id']:
                flash("Not Authorized")
                return redirect(url_for('posts.all', user_id=current_user.id))
            return f(*args, **kwargs)
        return wrapped
    return wrapper


@posts_blueprint.route('/posts', methods = ["GET"])
@login_required
def all():
    posts = Post.query.all()
    return render_template('all.html', posts=posts)

@posts_blueprint.route('/users/<int:user_id>/posts', methods = ["GET"])
@login_required
def index(user_id):
    user = User.query.get(user_id)
    return render_template('index.html', user=user)

@posts_blueprint.route('/users/<int:user_id>/posts/new', methods = ["GET"])
@login_required
@ensure_correct_user()
def new(user_id):
    user = User.query.get(user_id)
    form = NewPostForm(request.form)
    return render_template('new.html', user=user, form=form)

@posts_blueprint.route('/users/<int:user_id>/posts/<int:id>', methods = ["GET"])
@login_required
def show(user_id, id):
    post = Post.query.get(id)
    return render_template('show.html', user=post.user, post=post)

@posts_blueprint.route('/users/<int:user_id>/posts/<int:id>/edit', methods = ["GET"])
@login_required
@ensure_correct_user()
def edit(user_id, id):
    form = EditPostForm(request.form)
    post = Post.query.get(id)
    return render_template('edit.html', form=form, user= post.user, post=post)

@posts_blueprint.route('/users/<int:user_id>/posts', methods = ["POST"])
@login_required
@ensure_correct_user()
def create(user_id):
    user = User.query.get(user_id)
    form = NewPostForm(request.form)
    if form.validate_on_submit():
        new_post = Post(form.title.data, form.body.data, user.id)
        db.session.add(new_post)
        db.session.commit()
        flash("Post Successfully Added")
        return redirect(url_for('posts.index', user_id=user.id))
    else:
        return render_template('new.html', user=user, form=form)

@posts_blueprint.route('/users/<int:user_id>/posts/<int:id>', methods = ["PATCH"])
@login_required
@ensure_correct_user()
def update(user_id, id):
    error = None
    post = Post.query.get(id)
    form = EditPostForm(request.form)
    # VALIDATE ON SUBMIT ONLY WORKS WHEN THERE IS A POST!
    if form.validate():
        post.title = form.title.data
        post.body = form.body.data
        db.session.commit()
        return redirect(url_for('posts.index', user_id=post.user.id))
    else:
        return render_template('edit.html', form=form, user= post.user, post=post, error=error)

@posts_blueprint.route('/users/<int:user_id>/posts/<int:id>',methods=["DELETE"])
@login_required
@ensure_correct_user()
def destroy(user_id, id):
    post = Post.query.get(id)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('posts.index', user_id=post.user.id))

python/Exercises/flask_auth_multiple_resources/project/posts/templates/all.html
{% extends "base.html" %}

{% block content %}
    <a href="{{url_for('posts.new', user_id=current_user.id)}}">Add a new post</a> |
    <a href="{{url_for('posts.index', user_id=current_user.id)}}">See your posts</a>
    <h1>See all the posts</h1>
    {% for post in posts %}
    <p>
        USER_ID {{post.user.id}}| Title - {{post.title}} |
        <a href="{{url_for('posts.show', user_id=post.user.id, id=post.id)}}">Show</a> |
        <a href="{{url_for('posts.edit', user_id=post.user.id, id=post.id)}}">Edit</a>
        <form method="POST" action="{{url_for('posts.destroy', user_id=post.user.id, id=post.id)}}?_method=DELETE">
            <input type="submit" class = "btn btn-xs btn-danger" value="X">
        </form>
    </p>
    {% endfor %}
{% endblock %}

python/Exercises/flask_auth_multiple_resources/project/posts/templates/edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit an existing new post</h1>
<br>
<form method="post" action="{{url_for('posts.update', user_id=user.id, id=post.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title", value=post.title)}}
    <span class="text-danger">
      {% if form.title.errors %}
        {% for error in form.title.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.body(placeholder="body", value=post.body) }}
    <span class="text-danger">
      {% if form.body.errors %}
        {% for error in form.body.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-warning" type="submit">Edit</button>
</form>
{% endblock %}

python/Exercises/flask_auth_multiple_resources/project/posts/templates/index.html
{% extends "base.html" %}

{% block content %}
    <a href="{{url_for('posts.new', user_id=user.id)}}">Add a new post</a>
    <h1>See all of {{user.username}}'s posts - Your id is {{current_user.id}}</h1>
    {% for post in user.posts %}
    <p>
        USER_ID {{post.user.id}}| Title - {{post.title}} |
        <a href="{{url_for('posts.show', user_id=user.id, id=post.id)}}">Show</a> |
        <a href="{{url_for('posts.edit', user_id=user.id, id=post.id)}}">Edit</a>
        <form method="POST" action="{{url_for('posts.destroy', user_id=user.id, id=post.id)}}?_method=DELETE">
            <input type="submit" class = "btn btn-xs btn-danger" value="X">
        </form>
    </p>
    {% endfor %}
{% endblock %}

python/Exercises/flask_auth_multiple_resources/project/posts/templates/new.html
{% extends "base.html" %}

{% block content %}
<h1>Add a new post</h1>
<br>
<form method="post" action="{{url_for('posts.create', user_id=user.id)}}">
  {{ form.csrf_token }}
  <p>
    {{ form.title(placeholder="title") }}
    <span class="text-danger">
      {% if form.title.errors %}
        {% for error in form.title.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.body(placeholder="body") }}
    <span class="text-danger">
      {% if form.body.errors %}
        {% for error in form.body.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Add</button>
</form>
{% endblock %}

python/Exercises/flask_auth_multiple_resources/project/posts/templates/show.html
{% extends "base.html" %}

{% block content %}
<h1>See some more about {{post.title}}</h1>
<p>
    {{post.body}}
</p>
{% endblock %}